// Generated by CoffeeScript 1.3.3
(function() {
  var fs, jade, stitch;

  stitch = require('stitch');

  jade = require('jade');

  fs = require('fs');

  stitch.compilers.jade = function(module, filename) {
    var content;
    content = jade.compile(fs.readFileSync(filename, 'utf8'), {
      client: true
    });
    return module._compile("module.exports = " + content, filename);
  };

}).call(this);
